### ISSUE TITLE
 Trial Phases are missing from print search criteria under certain circumstances.

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/clinical-trials-search-app#178]
Steps:
1. Select all phases on the advanced search form (NOTE: Not the all option, but click each option)
2. On the results select some trials and click print selected.
3. Note the search criteria shows:
![image](https://user-images.githubusercontent.com/11215649/71221306-381db380-229a-11ea-8a16-a6ea577b55b9.png)

(This may be a bug in cgov)

**Comment by VictoriaSunNIH** [comment]
This was fixed as part of go live.
What's on Prod Now:
![image](https://user-images.githubusercontent.com/31222859/71529791-9bb86a00-28b4-11ea-98d1-ac83ab12097f.png)
