### ISSUE TITLE
Basic Form: We should enter 3 letters before getting the Cancer Type Dropdown

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/clinical-trials-search-app#180]
Current behavior:
On the Basic Form, the dropdown appears as soon as we click into the Cancer Type/Keyword field.

Expected Behavior:
A user should have to enter 3 or more letters before the dropdown appears -- this was the previous behavior on the old form.

**Comment by sarinapadilla** [comment]
The current behavior of having the dropdown appear when you click into the Cancer Type/Keyword field is now the expected behavior, so closing this ticket.
