### ISSUE TITLE
Trial Desc Page: Locations not showing option for "show all" when sites are 3 or less

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/clinical-trials-search-app#182]
Note: This may relate to a larger ticket to refactor locations.

Current Behavior:
When a trial has 3 or less sites, the "Show all locations" option under location does not show the toggle option for "show all" when you have other parameters to narrow the location.  

Expected Behavior:
Anytime there are other site locations outside of the range of the search , "Show all locations" should appear in that accordion.  

How to reproduce:
1. When running a search, select Limit results to Veterans Affairs Facilities toggle to "yes" and enter Zip code as 20850.
2. Navigate to a trial results page that has 3 locations, including 1 near you.
3. Go to the locations accordion, and note that there is no "locations near you" option in the accordion

**Comment by sarinapadilla** [comment]
Just tested this on react-app-dev and ODE, and this is no longer an issue. When viewing a trial that has 3 locations and 1 near you, the "Show all locations" link displays when initially opening the Locations & Contacts accordion, and "Show locations near me" displays after being switched to all locations. Closing this ticket.
