### ISSUE TITLE
Advanced Form: City and State are not cleared out when changing country selection

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/clinical-trials-search-app#183]
### Issue description
Currently on the advanced form, selected/entered values for State and City are not being cleared out when switching been the U.S. and non-U.S. countries.

> **ESTIMATE** TBD

### Steps to reproduce the issue: City not clearing out

1. Go to the advanced form and pick the Country, State, City location option (which defaults to the U.S.)
2. Enter a State and a City
3. Change the Country (for example, to United Kingdom)
4. Switch the Country back to the U.S.

### What's the expected result?
- The City field should be cleared after selecting a new Country
- When switching back to the U.S. again, both State and City should be cleared

### What's the actual result?
- The City field retains the value that was entered after selecting a new Country
- When switching back to the U.S. again, both State and City retain their values

### Additional details / screenshot
- ![Screenshot]()

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by sarinapadilla** [comment]
Possibly related to #483
