### ISSUE TITLE
Print Modal for 100 Trials Shows Error, then prints

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/clinical-trials-search-app#184]
Current Behavior:
If I select 100 trials, and click "print selected", the error modal first appears, letting me know i've selected more than 100 trials, but after a few seconds directs me to the print page.

Expected Behavior:
If 100 trials are selected, we should not get the error modal, and should see the printing results modal, followed by the results page.  The error modal should only appear on the 101st choice, and not allow users to print.

**Comment by sarinapadilla** [comment]
Closing this issue as we need to update the maximum number of trials to select for print to 20.
