### ISSUE TITLE
Find Trials option on advanced does not snap to form outside of XL mode

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/clinical-trials-search-app#185]
If you have a smaller screen, the Find Trials option that follows you on the Advanced Page breaks out of the form, and appears larger than the search fields.  This does not happen in XL mode.

On XL Screens (this is correct):
![image](https://user-images.githubusercontent.com/31222859/71530456-de2f7600-28b7-11ea-8c7f-9f3f9499b3ae.png)

On Smaller Screens (this is incorrect):
![image](https://user-images.githubusercontent.com/31222859/71530438-c952e280-28b7-11ea-818f-0953fd668493.png)

**Comment by sarinapadilla** [comment]
Closing this issue as it was not able to be reproduced.
