### ISSUE TITLE
Pager Issues (it always adds one when I paste the URL or use back button)

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/clinical-trials-search-app#187]
The current pager on CTS Search has an issue where if I paste the URL, the pn number is incremented by 1.  This affects multiple scenarios:
1. If I copy and paste the search results page, if I copied page 1, it will direct me to page 2 when I paste the URL and navigate to it.
2. If I am on a different URL (like the print page), and click the "back" button in my browser, it will direct me to the page incremented by one.  This breaks especially if I was on the last page of results (for example, page 4), then went to print, and then hit back, because it tries to go to page 5, but page 5 does not exist, leading me to a blank screen.
3. If you click "Next" on the pager to get to pn=4, and then use the back button, it goes to pn=3, pn=2, pn=1 (each displaying the results for that page) then jumps back up to pn=3, pn=2 and no pn query param but for those, the displayed page still stays the same, only the query params change. Then finally back to search. So when I clicked through the pager to page 9, then used the back button, I had to click 8 times after back on page 1 of results to get back to the search page

**Comment by sarinapadilla** [comment]
This was fixed with PR #474, so closing this ticket.
