### ISSUE TITLE
Updates to No Results Found Page

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/clinical-trials-search-app#196]
The message "No clinical trials matched your search." appears twice on a no results page.  

It should look like the comp below:

**Comment by mworrest** [comment]
![NO RESULTS](https://user-images.githubusercontent.com/4921685/71599510-1e416380-2b19-11ea-8086-efbe7bf02b42.jpg)

**Comment by adriancofie** [comment]
We're removing the duplicate, but are we changing the text of the remaining one from "No clinical trials matched your search." to "No search results found"  (What's in the screenshot)

@VictoriaSunNIH @sarinapadilla

**Comment by sarinapadilla** [comment]
@adriancofie keep it as "No clinical trials matched your search" please!
