### ISSUE TITLE
Modify search from Trial Details Page

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/clinical-trials-search-app#201]
Can we please add a modify search link on the Trial Details page?  It should be on the same line as Start Over, with an option to "Modify Search Criteria" and lead us back to the advanced form with the search terms pre-populated.  (it should look like it does on the search results page, below the search accordion, with both options on the same line "Start Over | Modify Search Criteria")

**Comment by alinai** [comment]
Looks good to me. Thanks @alerosad!
