### ISSUE TITLE
CTS No Trials Match Search page Live Help going to wrong queue

### ISSUE THREAD

**Issue by amydugan** [NCIOCPL/clinical-trials-search-app#203]
CTS No Trials Match Search Page is going to the regular Cancer Information LiveHelp queue instead of the CTS LiveHelp queue.

Issue Reported by CIS on 1/16:
When filling out the search form, if your selection does not turn up any clinical trials, you receive this message (found on https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/r?loc=1&rl=2&st=C66719&t=C4872&z=26554&zp=20):

No clinical trials matched your search.
For assistance, please contact the Cancer Information Service. You can chat online or call 1-800-4-CANCER (1-800-422-6237).
Try a new search

Actual result:
The “chat online” is clickable and goes directly into our LiveHelp queue. However, we realized that the queue it directs to is incorrect—it takes you to the Cancer Information queue and not the Clinical Trials queue as it should. 

Expected result: 
The "chat online" is clickable and goes directly into the Clinical Trials queue within LiveHelp. The link should pass the parameter icf_22 = 2174, so the link is https://livehelp.cancer.gov/app/chat/chat_landing?_icf_22=2174

**Comment by venglisch** [comment]
A couple of things to note:
1. For testing purposes please use the URL https://nci--tst.custhelp.com. This URL points to the LiveHelp test site which doesn't start an actual chat with the CIS
2. Following a link to the LiveHelp chat is typically done in a separate window.  You end up with a huge banner if you're following the link in a regular window.
3. Last time we had looked at "accessing the chat via link" - I believe it was for the Quit Smoking site - we identified it wasn't doable and called the LiveHelp chat window instead: https://livehelp.cancer.gov.
You will probably have to use a form if you want to start a chat without going through the LiveHelp page.
You will likely have to create a form and style it like a regular link.  See https://smokefree.gov, they have done that in their footer - with the caveat of (2).

**Comment by blairlearn** [comment]
@venglisch is correct. If you try to access the chat via a simple link (i.e. a GET request), you end up with a "default" channel.  To get a specific one, you have to use a POST request.

Also note that directly linking/posting into the chat system isn't something that's directly supported. When we figured out how to do this for smokefree.gov, and later, for the cancer moonshot, this functionality was something of a "hack."
