### ISSUE TITLE
Print Locations not appearing when user manipulates zipcode radius

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/clinical-trials-search-app#206]
### Issue description
When a user changes the zipcode radius parameter in the URL (outside of the ones we normally allow in search which is 20, 50, 100, 200, 500), and that is resulting in the locations not appearing once they select trials and click "print", instead pointing the user to ClinicalTrials.gov to look for locations.  

> **ESTIMATE** 20

### Steps to reproduce the issue

1.  Go to https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/r?a=59&loc=1&rl=2&stg=C134195%7CC89998%7CC8516&stg=C8625&t=C2955&tt=treatment&z=19019&zp=20
2. Select a few trials (specifically, you can select:
    * Vitamin D3 With Chemotherapy And Bevacizumab In Treating Patients With Advanced Or Metastatic Colorectal Cancer, SOLARIS Trial
    * Trastuzumab And Pertuzumab Or Cetuximab And Irinotecan Hydrochloride In Treating Patients With Locally Advanced Or Metastatic HER2 / Neu Amplified Colorectal Cancer That Cannot Be Removed By Surgery
    * Targeted Therapy Directed By Genetic Testing In Treating Patients With Advanced Refractory Solid Tumors, Lymphomas, Or Multiple Myeloma (The MATCH Screening Trial)
3. Go to the print page, and note that locations show those closest to the zip radius entered
4.  Change the zp=20 to zp=5
5.  Select the same trials on the page
6. Note that the locations and contacts section now shows the text "Note: Information about participating sites on pharmaceutical industry trials may be incomplete, so please look up the NCT number on ClinicalTrials.gov"

### What's the expected result?
Users should see the locations within the radius entered (even if its not one of the radii we provided in the search)

### What's the actual result?
Currently, users are being directed to ClinicalTrials.gov to look for locations when locations actually do exist within the radius entered

### Additional Notes
A copy of the original email from CIS is included below for reference:

> One of our information specialists ran into a glitch when the list of selected clinical trials was converted to print; the locations disappeared.  Even when contact information is not provided, for example, when the sponsor is a pharmaceutical company, the participating sites are listed.  It appears that this information was stripped out when the search was converted to print because the locations appear in the original results.  We’ve not encountered this before and wondered if the CT database engineers might have any ideas as to why this occurred.

> When a ZIP code is entered, there are standard mile radii provided:  20, 50, 100, 200, and 500.  However, you can alter the mileage in the URL of the search to specify other distances and we routinely do that.  Specifying a mileage has not resulted, that we know of, in locations being stripped out in the print version.  However, it does appear that may be what happened in this case.  When I searched at 20 miles and selected the first 10 trials, the locations are intact in the print version.  

> The first link is the original search, as delivered by the search tool.  The 2nd link is to the first 10 trials from the search, selected, and converted to print.

> List of trial results, manually inputted 5 miles of ZIP code 19019, prior to selecting trials and printing
https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/r?a=59&loc=1&rl=2&stg=C134195%7CC89998%7CC8516&stg=C8625&t=C2955&tt=treatment&z=19019&zp=5

> List of trials in print format (5 miles of ZIP code 19019) – location information stripped out
https://www.cancer.gov/CTS.Print/Display?printid=259c3d23-26f9-ea11-8184-0050568e168e

> List of trials in print format (20 miles of ZIP code 19019) – location information intact
https://www.cancer.gov/CTS.Print/Display?printid=eb28af3a-28f9-ea11-8184-0050568e168e

> It’s a mystery why this happened.  The CTS sent the search from ct.gov so that the locations would be available to the client.

**Comment by sarinapadilla** [comment]
Closing this ticket as the issue did not persist during re-testing.
