### ISSUE TITLE
Trial Details location filter does not handle US territories except Puerto Rico.

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/clinical-trials-search-app#226]
### Issue description
Trials have started being reported in Guam (a territory). This results in the location filter on the trial details page displaying a blank line in a random location.

This appears to happen because the state list in `src/utilities/getStateNameFromAbbr.js` doesn't include any territories other than Puerto Rico.

> **ESTIMATE** 2

### Steps to reproduce the issue

1.  Navigate to the details page for a trial with sites in a territory other than Puerto Rico.  (As of this writing, NCT02201992 has sites in Guam. So..   https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/v?id=NCI-2014-01507&loc=0&rl=1)
2. Expand the "Locations and Contacts" accordion.
3. Expand the "State" dropdown

### What's the expected result?
- All states should display a name.

### What's the actual result?
- The select list entry for Guam (GU) shows a blank.

### Additional details / screenshot
- ![image](https://user-images.githubusercontent.com/21063180/115749802-7bdc6d80-a365-11eb-9410-fe1448f8c9a9.png)
- ![image](https://user-images.githubusercontent.com/21063180/115749854-85fe6c00-a365-11eb-93c7-f1b6a9183558.png)

### Related Tickets
*

**Comment by alerosad** [comment]
I don't see the mentioned bug 
<img width="1792" alt="Screen Shot 2022-04-25 at 1 30 56 PM" src="https://user-images.githubusercontent.com/73490679/165142429-a3712061-cbcf-4e90-9423-85dc9ad2bffe.png">

**Comment by alerosad** [comment]
I don't see the mentioned bug
<img width="1792" alt="Screen Shot 2022-04-25 at 1 33 10 PM" src="https://user-images.githubusercontent.com/73490679/165142674-6bd53003-b4aa-4c7e-9102-e5ec148a06e7.png">

**Comment by alerosad** [comment]
I checked the feature branch too, and didn't see this issue come up on the example you provided Blair

**Comment by alerosad** [comment]
Both Develop and feature seem to not have this issue

**Comment by KateMashkinaNIH** [comment]
this was fixed
