### ISSUE TITLE
Apply Linting Rules

### ISSUE THREAD

**Issue by seyilonge-nci** [NCIOCPL/clinical-trials-search-app#253]
### Apply Linting Rules to newly added and modified files 
*Create linting rules, update prettier rules, add github action for linting*

> **ESTIMATE** 3

### What's the expected change?
-

### What's the current functionality?
-

### What's the updated acceptance criteria?
```gherkin
```

### Additional details / screenshot
- ![Screenshot]()

### Related Tickets
* Original Story Ticket #9999
* Original Story Ticket #9999

**Comment by bryanpizzillo** [comment]
This ticket should just be for configuring the linting rules. Any additional work on github actions should be another ticket.
