### ISSUE TITLE
[Meta] Upgrade CTS to Use CTS API v2

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/clinical-trials-search-app#269]
We need to update the application to use the new CTSAPI. This meta ticket should cover all of activities for this endeavor.

### Tickets 
- [x] #271
- [x] #268
- [x] #296
- [x] #270
- [x] #267 (SP:1)
- [x] #364 (SP:2)
- [x] #334
- [x] #204
- [x] #407
- [x] #391

**Comment by sarinapadilla** [comment]
Closing this meta ticket, as all of the tasks are completed!
