### ISSUE TITLE
Break down Location section tests (#230) into separate features

### ISSUE THREAD

**Issue by kate-mashkina** [NCIOCPL/clinical-trials-search-app#287]
*Description of what is to be accomplished.*
The location section tests should really be compiled of separated features : zipcode,  country and hospitals
Should be done 
**Parent Issue:** #9999

### Sub-Tasks
- [ ] Create Component
- [ ] Implement Unit Tests for Component

### Notes

*Some complementary notes if necessary:*
* > Here goes a quote from an email
* Here goes whatever useful information can exist…
* More notes, or technical nuances/direction

**Comment by bryanpizzillo** [comment]
I suggest the features be:
* All
* Zip
* Country, State, City
* Hospital
* NIH
* VA, containing scenarios for
   * All
   * Country, State, City
   * Zip
