### ISSUE TITLE
Spike: Identify Approach to Remove Redux from CTS App

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/clinical-trials-search-app#296]
## In order to remove Redux from the CTS App a developer needs to identify an approach to remove redux.

> **Estimation** *whatever* 

### Expected Deliverables:
* A plan of attack that is iterative.
   * What are the hooks to be implemented?
   * What are the "actions" for the API calls? 
* A set of stories to be created that implement that plan
   * Each story should leave the system in a state where all tests pass!
   * The last story should be removing the old reducer and actions.

### Additional Notes/Questions:
* The probably starts with figuring out how to get our app context setup like we do with other apps.
* Are there any modules we need to update first to make this work better?
   * For example react router to handle params better... (not saying it has to be updated.)
   * These modules must NOT require redux to be updated, or at least not updated to a version that would require major changes.  
* The app uses much more state between the search form, results and viewing a trial than our other apps. It *may* make sense to create a higher order component to handle mapping of query params to search criteria. 
   * This should not be like the oddball HOC from the listing pages were we have to wrap each component.
* The fetching from the API should be like what we have with the listing pages and `useCTSApi`. (And by should I mean, SHALL)
   * The only thing questionable here is how do we handle multiple calls to the API for things like the initial load of the Advance search form. 
      * For example, I don't want 5 calls to useCTSApi at the top of the form with multiple states and a bunch of isLoading checks.
      * I could do with an "action" that defines multiple calls to be fetched. Or this could even just be an array of actions passed in to be fetched.
      * We want to make sure we limit the number of redraws and whatnot for the apps. We may need to useReducer on the views though as a lot of state needs to be tracked.

### Results of Spike
*Enter the information, or links to any (non-sensitive) files with the findings here*

**Comment by seyilonge-nci** [comment]
Form
————
Since forms and their states are encapsulated within the page it resides. We can do away with having this in the global state. Look into using react-hook-form
Tracking
——————-
This can be implemented as a custom hook using a reducer with the initial state shape clearly defined, and action dispatchers to handle tracking events
with defined actions.


Pages
—————

1. SearchPage
	- Extract selectors to inline hooks
2. ResultsPage

3. TrialDescriptionPage

**Comment by seyilonge-nci** [comment]
![ CTS-Overview](https://user-images.githubusercontent.com/58226882/134567394-ab20015d-c461-41db-81a9-d0544aed3d6c.png)
![SearchCriteria](https://user-images.githubusercontent.com/58226882/134567412-65a0aae4-bbb1-491a-80e9-f4e302b03704.png)

**Comment by bryanpizzillo** [comment]
Tasks:
- [ ] Update Global Store (Global State becomes a globally available context)
- [ ] Update Trial Description & Trial Results to use query params instead of redux.form (Results Page)
        * This should still update redux in the event a url was pasted in... 
           * This makes Modify search work
        * This should use new fetch methods for trial results and trial description itself
- [ ] Update Search Criteria to use search criteria object (Search Criteria Box)
        * This control should handle its own fetching and caching and whatnot.
        * Make the fetchers for this too
- [ ] Implement Print checkbox checking
       * Needs to maintain state across results pages and trial description
- [ ] Fix the"questionable" pager

**Comment by bryanpizzillo** [comment]
This is now closed as @seyilonge-nci and @arcepaul updated #334 and created tickets from that.
