### ISSUE TITLE
Linting Error: Do not export from a test file jest/no-export (7)

### ISSUE THREAD

**Issue by adriancofie** [NCIOCPL/clinical-trials-search-app#307]
### Issue description

The following linting error(s) appears in the subsequent file(s):

(7) Do not export from a test file jest/no-export

    /src/utilities/__tests__/queryStringToFormObject.common.js
    /src/utilities/__tests__/defaultStateCopy.js

> **ESTIMATE** TBD

### Steps to reproduce the issue

1. ` npm run lint:fix`

**Comment by bryanpizzillo** [comment]
I think we should just add the linter ignore above each export
`// eslint-disable-next-line jest/no-export`

The files export because there is so many constants and large blobs of data we did not want copy/paste everywhere.
