### ISSUE TITLE
[META] Replace Redux Part 1

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/clinical-trials-search-app#334]
In order to modernize the CTS App following our hook implementations, we need to remove redux. This will reduce the complexity with the implementation and make it easier to update in the future. Given the high-LOE of this, we will break this into 2 parts. Everything we can do before the CTS API v2 upgrade (this ticket), and then everything after that point. (#405)
 
- [x] #350 (SP:3)
- [x] #346 (SP:5)
- [x] #347
- [x] #401
- [x] #404

**Comment by sarinapadilla** [comment]
Closing this meta ticket, as all of the tasks are completed!
