### ISSUE TITLE
Fix complicated components so they no longer use Redux + middleware

### ISSUE THREAD

**Issue by arcepaul** [NCIOCPL/clinical-trials-search-app#339]
### As a developer I want to refactor components so that they no longer refer to the redux store or make use of redux middleware so that the components are more easily testable and maintainable.

> **ESTIMATE** TBD

### Notes

Go through components and remove references or any mechanisms which reference the redux global store.  Simplify and refactor components where it makes sense.  Components should be as "dumb" as possible.  For search module components/molecules, there is some standardization that can occur.

---

### Prerequisites
- [ ] Search modules folder moved to be under search page view

#### Atomic
Below is a quick list of atomic components which at a quick glance are interacting with the redux store
- [ ] Checkbox
- [ ] Dropdown
- [ ] Radio
- [ ] SearchCriteriaTable
- [ ] StickySubmitBlock
- [ ] TextInput
- [ ] Toggle

Finale:
- [ ] https://github.com/NCIOCPL/clinical-trials-search-app/issues/343

**Comment by sarinapadilla** [comment]
This ticket will be addressed by the stories to come out of #374 .
