### ISSUE TITLE
Refactor CTS Pager component

### ISSUE THREAD

**Issue by arcepaul** [NCIOCPL/clinical-trials-search-app#341]
### As a developer, refactor the CTS pager component so that it does not cause unnecessary rerenders and is more performant.

> **ESTIMATE** 5

---

## Solution
Implement the most recent form of the pager from react-playground, or one of the more recent projects using the pager.

### Technical Notes
- The current CTS pager is based on the R4R pager and is very closely intertwined with the redux global store and results "caching" scheme
- Remove dependence on redux stores and middleware
- Eliminate unnecessary re-renders (using the pager should only cause rerenders of the results list and supporting bits, not the entire results page
- Fix any console warnings

**Comment by bryanpizzillo** [comment]
@arcepaul is this still correct? 
* There is no redux in the pager component
* I thought the odd page incrementing was the failure of the TrialResults page, and that our update to react-router v6 fixed this.
