### ISSUE TITLE
Implement Print Checkboxes on Results Page

### ISSUE THREAD

**Issue by arcepaul** [NCIOCPL/clinical-trials-search-app#342]
### As a developer, implement a context or HOC to store selected results array for print checkboxes so that it doesn't use the redux global store so that redux can be removed safely.

> **ESTIMATE** 8

---

### Technical Notes
* Currently the Print IDs are stored in the redux store, but these need to be removed in order to remove Redux
* The are put into the store by:
   * Check all (all on ResultsPage)
      * handleSelectAll calls 
      * setSelectedResults that triggers 
      * a useEffect + [dispatch for selectedTrialsForPrint](https://github.com/NCIOCPL/clinical-trials-search-app/blob/develop/src/views/ResultsPage/ResultsPage.jsx#L157)
   * Selecting a single item
     * Click the Check Box on ResultsListItem triggers
     * onCheckChange (handleOnCheckChange function passed in from ResultsList) calls
     * Either setSelectAll or setSelectedResults (passed in from ResultsPage) triggers
      * a useEffect + [dispatch for selectedTrialsForPrint](https://github.com/NCIOCPL/clinical-trials-search-app/blob/develop/src/views/ResultsPage/ResultsPage.jsx#L157)
* Needs to maintain state across results pages and trial description
* needs to clear out on search execution
* What should happen when you go: Search -> Results -> Start Over -(back button) -> Results? Should it keep the check boxes?
* Tracking involved: number of items in list

## Approach
* Create a context + hook for print results. 
* Wrap the router with the context -- it must be the same instance of the context.
* This "context" should be implemented with useReducer
* the following functions should be made available by the hook:
  * selectedTrials - gets a list of the selected trials
  * addSelectedTrial - adds one or more trial IDs to the list
  * removeSelectedTrial - removes one or more trial ids from the list
  * unselectAllTrials - removes all trials from the list (to be called by Basic and Advanced Search Pages on new search)
* @seyilonge to prototype approach

**Comment by seyilonge-nci** [comment]
NOTE:
Currently when "Select all on page" checkbox is checked on the results page, clicking on a trial description and using the "< Back to search results" link does not have the "Select all on page" checkbox checked by default, though trial results on the page are all selected.

**Comment by sarinapadilla** [comment]
Implement this as a feature branch.

We will break this out into two stories:
- One to create the context
- One to wire up the checkboxes
