### ISSUE TITLE
Update Trial Results to use query params

### ISSUE THREAD

**Issue by arcepaul** [NCIOCPL/clinical-trials-search-app#362]
### As a developer, update the Trial Results views to be hydrated via the query parameters so that the dependence on the redux store for the pages is removed.
For the time being, until redux is ready to be removed, this should still update redux in the event a url was pasted in.

> **ESTIMATE** 8

### Prerequisites
- #350 

### Tasks
- [x] #379 
- [x] #380 
- [x] #381 
- [x] #382 
- [x] #383

**Comment by bryanpizzillo** [comment]
NOTE:
1. The `useStoreToFindTrials` hook should be removed. The logic implemented to fetch trials will replace that.

**Comment by sarinapadilla** [comment]
Closing this ticket, as we've addressed all of the tasks that are part of this story.
