### ISSUE TITLE
Spike: Initial Implementation of React-Form on search page

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/clinical-trials-search-app#376]
## In order to update the search page with React Form, we need to determine an approach for completing the initial tasks for implementation.

This spike should determine an approach for implementing React-Form, along with what common elements are needed for it to scale for all of our search components. Context, configs, etc.

This involves:

- [ ]  install react-hook-form, manage react-hook-form state and current state in Redux
- [ ] what react-hook-form needs to pass to the search components
- [ ] what context is needed, and what standardization can happen across the search modules
- [ ] analytics tracking based on react-hook-form state
- [ ] Fix CI build process warnings (and don't create new ones)
- [ ] We need to create a function to convert the react-form to a "formState" to be used by buildQueryString
- [ ] making sure react-hook-form is the solution we're looking for

> **Estimate ** *5* 

### Expected Deliverables:
* Approach to break down #344 into stories
* Documentation of these new stories

### Additional Notes:
* React Hook Form: [https://react-hook-form.com/](https://react-hook-form.com/)
* Technical Notes:
  * New library to be brought in that tracks items on form for us: React Form
  * React Form contains utilities that can replace Redux: tracking, validation, etc.
  * Fix modify search from "Update Trial Description & Trial Results" above to pass search criteria object in location state. Then have search page rehydrate React-Form/Components based on that state.
  * Complicated components using chips should still update redux store. (This to be fixed in: Fix complicated components so they no longer use Redux + middleware #339)
  * Search modules will still use middleware for API calls

### Results of Spike
*Enter the information, or links to any (non-sensative) files with the findings here*

**Comment by bryanpnih** [comment]
Based on a few long discussions this has been figured out and tickets created. Closing this ticket to avoid confusion.
