### ISSUE TITLE
Spike: Determine approach for updating Trial Results page using Query Params

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/clinical-trials-search-app#378]
## In order to update the Trial Results page using Query Params, we need to determine an approach that breaks out the main story into smaller ones.

> **Estimated Timeframe** *# of days for completion* 

***NOTE: a single story point is about 1 day.  A spike should not go on for than 2 days, otherwise it is too big, or it needs to be an enabler and estimated.***

### Expected Deliverables:
*Examples:*
* A new set of stories breaking down https://github.com/NCIOCPL/clinical-trials-search-app/issues/362

### Additional Notes:
* note 1

### Results of Spike
*Enter the information, or links to any (non-sensitive) files with the findings here*

Tasks
- [ ] Utility function needs to be created to convert url query string to form object (determine form object structure. We'll be using the api search params. Need to list this all out.)
- [ ] Utility function `objectToQuerystring` currently implemented in file `utilities/buildQueryString.js`
- [ ] Utility function `queryStringToObject` currently implemented in file `utilities/queryStringToFormObject.js`
- [ ] Pull over methods from CTL (Listing App)
Clinical Trials Listings API from CTL (App already makes this call) - https://github.com/NCIOCPL/clinical-trials-listing-app/tree/develop/src/services/api/clinical-trials-search-api
- [ ] useEffect to properly apply utility function
- [ ] Remove redux (references to form object and results caching)

**Comment by adriancofie** [comment]
@sarinapadilla can be closed

**Comment by sarinapadilla** [comment]
Closed with PRs #386 , #388 , #387 , #459
