### ISSUE TITLE
[META] Remove Redux from Trial Results

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/clinical-trials-search-app#401]
This meta ticket is to roll up all the tasks that are needed for removing Redux from Trial Results. 

- [x] #378 
   * This should be closed and tickets should already be created.
- [x] #395 
- [x] #408
- [x] #362
- [x] #392
- [x] #342
- [x] #403
- [x] @arcepaul to review ---> #341

**Comment by sarinapadilla** [comment]
Closing this meta ticket, as we've completed all of the tasks!
