### ISSUE TITLE
[META] Update Advanced Search Middleware to remove the CTS Client stuff

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/clinical-trials-search-app#406]
The clinical-trials-search-client.js package will not be updated for CTS API v2. (It is a pain to keep updated, it really is unnecessary, and it does not even cover all of the endpoints needed.) The CTS Middleware is entirely based on the CTS client. Fetchers will need to be implemented for v2 for each of the store actions having to do with the CTS API.

- [x] #444
- [x] #417
- [x] #418
- [x] #419
- [x] #420
- [x] #421
- [x] #422
- [x] #423
- [x] #424
- [x] #425
- [x] #426 
- [x] #416

**Comment by sarinapadilla** [comment]
Closing this meta ticket, as all of the tasks are completed!
