### ISSUE TITLE
[META] Implement Updated v2 Calls to the API and Updated Responses

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/clinical-trials-search-app#407]
So this ticket is the actual "go update things to use CTS API v2".

### Tickets
- [x] #389
- [x] #390
- [x] #443
- [x] #406 
- [x] #412
- [x] #409
- [x] #410
- [x] #413

**Comment by sarinapadilla** [comment]
Closing this meta ticket, as all of the tasks are completed!
