### ISSUE TITLE
Update ctsapiInterventionFetcher utility to fetch from v2

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/clinical-trials-search-app#410]
This should also be moved to the services/clinical-trials-search-api folder. It should also be updated to use the raw axios client instead of the clinical-trials-search-client.js.

This also involves updating mock data and unit tests.

> **ESTIMATE** 2

**Comment by sarinapadilla** [comment]
Fixed with PR #454, so closing this ticket.
