### ISSUE TITLE
Pull out degreeToRadian() function from isWithinRadius

### ISSUE THREAD

**Issue by arcepaul** [NCIOCPL/clinical-trials-search-app#432]
### The function degreeToRadian is currently a function embedded inside of the utility isWithinRadius(), meaning that this function is recreated every time that isWithinRadius is called, which can be hundreds of times per list of results displayed on the results page.  

---
## Solution
- [ ] Pull out degreeToRadian from the isWithinRadius() function (e.g. move to top outside of function)
- [ ] Create unit test for the isWithinRadius

**Comment by sarinapadilla** [comment]
Fixed with #458, so closing this ticket.
