### ISSUE TITLE
Remove redux bit from pagination on results page

### ISSUE THREAD

**Issue by arcepaul** [NCIOCPL/clinical-trials-search-app#433]
Looking at the code, handlePagination() on ResultsPage.jsx updates the redux store with the current page.  This call can/should be eliminated and not use redux at all for functionality.

---

## Solution
Remove the handleUpdate call in handlePagination.  The current page can be derived for pager use from the query string or search criteria object.

**Comment by sarinapadilla** [comment]
This ticket will be completed with the work completed on #392. When PR #430 is pulled in, we can close this ticket.
