### ISSUE TITLE
Update Trial Description page to use CTS API V2

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/clinical-trials-search-app#443]
Tasks:

- [ ] Update getClinicalTrialDescription method to use API v2
`const res = await client.get(`/trials/${id}`);`
   - [ ] Update mock data and unit tests 
   Note: pasted V2 response into mocks and it works out of the box, so go through every mock and just replace responses 
- [ ] Update Trial Description page
   - Update drawing all of the trial fields 
fields should work **as is** with V2 ( as long as trialDescription from localState object is correct)

https://clinicaltrialsapi.cancer.gov/breaking-changes

**Comment by kate-mashkina** [comment]
merged
