### ISSUE TITLE
Blank page displays intermittently when clicking/copying a URL

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/clinical-trials-search-app#462]
### Issue description
So this is a weird, intermittent issue.

A client reported that when she clicked (or copied, not sure) [this URL](https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/r?d=C923%7CC15347&loc=0&pn=2&rl=2&t=C2955&tt=treatment) from a previous search, she got a blank page. Another client reported that the trial results loaded correctly for her. When I clicked or copied the URL, I was most often redirected to [this URL](https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/r?d=C923%7CC15347&loc=0&pn=3&rl=2&t=C2955&tt=treatment) (with a different pn query param than the original URL), but the trial results loaded for that page number. Very intermittently, I was redirected [here](https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/r?d=C923%7CC15347&loc=0&pn=3&rl=2&t=C2955&tt=treatment) again, but then saw a blank page.

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  Go to https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/r?d=C923%7CC15347&loc=0&pn=2&rl=2&t=C2955&tt=treatment
2. Either:
   1. The page redirects to the third page of results and shows the trial results
   2. The page redirects to the third page of results and shows a blank page

### What's the expected result?
- The page should not redirect, and show the second page of results with the trial results

### What's the actual result?
-  Either:
   1. The page redirects to https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/r?d=C923%7CC15347&loc=0&pn=3&rl=2&t=C2955&tt=treatment and shows the trial results for that page number
   2. The page redirects to https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/r?d=C923%7CC15347&loc=0&pn=3&rl=2&t=C2955&tt=treatment and shows a blank page

### Additional details / screenshot
![image002](https://user-images.githubusercontent.com/24591940/150377873-5e25cc90-4fd1-4323-b75a-91b538ccd859.jpg)

**Comment by adriancofie** [comment]
@sarinapadilla This is related to https://github.com/NCIOCPL/clinical-trials-search-app/issues/187. The URL being displayed is not actually in sync / directly tied to the data being displayed on the page, it's a bit of a facade. Currently when a search is directly pasted in, after it loads, the 'pn' is incremented by 1 and the url is erroneously updated. It does not actually navigate however.  If someone hits refresh at this point, it attempts to load the incremented page, not the original one.   In the case of your example there is no additional page after 'pn' = 2, so 'pn' = 3 returns a blank page.  

It's also worth noting that the 'pn' and the pager values similarly get out of sync depending on how you navigate.
