### ISSUE TITLE
Clinical Trials API v2 returns duplicates for Interventions endpoint requests

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/clinical-trials-search-app#486]
### Issue description
Currently, the Clinical Trials API v2 is returning the term name as a duplicate in the synonyms on all requests to the /interventions endpoint.

For example, a request to https://clinicaltrialsapi.cancer.gov/api/v2/interventions?current_trial_status[]=Active&current_trial_status[]=Approved&current_trial_status[]=Enrolling%20by%20Invitation&current_trial_status[]=In%20Review&current_trial_status[]=Temporarily%20Closed%20to%20Accrual&current_trial_status[]=Temporarily%20Closed%20to%20Accrual%20and%20Intervention&sort=count&order=desc&category[]=Other&name=polymo&size=10 returns
```
{
    "data": [
        {
            "name": "Polymorphism Analysis",
            "codes": [
                "C18309"
            ],
            "category": [
                "other"
            ],
            "type": [
                "genetic"
            ],
            "synonyms": [
                "Polymorphism Analysis",
                "Polymorphism Detection"
            ],
            "count": 1
        }
    ]
}
```

A workaround needs to be implemented to remove this duplicate item from the list of `synonyms`, until the API fixes this bug.

> **ESTIMATE** 5

### Additional details / screenshot
- ![Screenshot]()

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by seyilonge-nci** [comment]
Resolved through PR #497
