### ISSUE TITLE
Start Over link from Trial Description page doesn't clear the form fields

### ISSUE THREAD

**Issue by kate-mashkina** [NCIOCPL/clinical-trials-search-app#487]
### Issue description
*Description of the issue*
When you hit Start Over link from any Trial Description page that has any parameters ( e.g. /about-cancer/treatment/clinical-trials/search/v?a=78&id=NCI-2014-01507&loc=0&rl=2) - it does not clear the form field, but populates it with query param  values 

Whereas Prod clears the form state (https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/v?a=56&id=NCI-2014-01507&loc=0&rl=2 )
> **ESTIMATE** 3

### Steps to reproduce the issue

1.  Navigate to any trial page with extra param, such as /about-cancer/treatment/clinical-trials/search/v?a=78&id=NCI-2014-01507&loc=0&rl=2
2. Click Start Over
3. See the Age field populated with the value

### What's the expected result?
- Form state should be cleared

### What's the actual result?
- Form populates with values

### Additional details / screenshot
- ![Screenshot]()

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by adriancofie** [comment]
Possibly related to https://github.com/NCIOCPL/clinical-trials-search-app/pull/484

**Comment by alerosad** [comment]
Spoke with Adrian, he mentioned that https://github.com/NCIOCPL/clinical-trials-search-app/issues/483 , which he is currently working on, should resolve this issue
