### ISSUE TITLE
Make content URLs configurable

### ISSUE THREAD

**Issue by kate-mashkina** [NCIOCPL/clinical-trials-search-app#488]
### Issue description
With the relocation of all clinical trials information content from `/about-cancer/treatment/clinical-trials` to `/research/participate/clinical-trials`, all of the hardcoded intro text, help, and delighter links are pointing to the incorrect place. We need to update the app to use values passed in through the app module config to set the URL for these links.

> **ESTIMATE** TBD

### What's the expected change?
- The app module config passes the URLs for the intro text, help, and delighter links.

### What's the current functionality?
- The URLs for the intro text, help, and delighter links are hardcoded within the app.

### What's the updated acceptance criteria?
```gherkin
Scenario: Help link URLs are configurable  
Given baseUrl is set to "https://www.cancer.gov"
  And helpUrl is set to "/research/participate/clinical-trials-search/help"
Then Age help link has an href "https://www.cancer.gov/research/participate/clinical-trials-search/help#age"
```

```gherkin
Scenario: CTS What delighter link is configurable 
Given baseUrl is set to "https://www.cancer.gov"
  And whatAreTrialsUrl is set to "/research/participate/clinical-trials/what-are-clinical-trials"
Then the 'CTS What' delighter has an href "https://www.cancer.gov/research/participate/clinical-trials/what-are-clinical-trials"
```

```gherkin
Scenario: Intro text and CTS Which delighter links are configurable 
Given baseUrl is set to "https://www.cancer.gov"
  And whichTrialsUrl is set to "/research/participate/clinical-trials-search/steps"
Then the 'CTS Which' delighter has an href "https://www.cancer.gov/research/participate/clinical-trials-search/steps"
  And the 'Steps to Find a Clinical Trial' intro text link has an href "https://www.cancer.gov/research/participate/clinical-trials-search/steps"
```

### Additional details / screenshot
- ![Screenshot]()

### Related Tickets
* Original Story Ticket #9999
* Original Story Ticket #9999

**Comment by SupriyaSaxena0605** [comment]
@sarinapadilla the tests pass on test-ac for this ticket
