### ISSUE TITLE
filterSitesByActiveRecruitment is throwing console error when sites are null 

### ISSUE THREAD

**Issue by kate-mashkina** [NCIOCPL/clinical-trials-search-app#492]
### Issue description
*Description of the issue*
This issue was discovered while testing pr#478 - when you navigate to https://react-app-dev.cancer.gov/clinical-trials-search-app/pr-478/r?loc=0&rl=1&t=C9278 
1) first trial has empty Location: , where as it should be **See [ClinicalTrials.gov](http://clinicaltrials.gov/)**
2) clicking that trial will not load trial description page - there is a console error 
<img width="1062" alt="Screen Shot 2022-03-10 at 1 02 49 PM" src="https://user-images.githubusercontent.com/56886837/157726536-09708df4-715f-4e49-a470-427fcd6d8733.png">

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  
2. 
3. 

### What's the expected result?
-

### What's the actual result?
-

### Additional details / screenshot
Notes:
feature/cts-api-v2 branch does not have a problem displaying Location: See [ClinicalTrials.gov](http://clinicaltrials.gov/) , but still loading a blank page in place of trial description page - I was able to fix that locally by guarding sites
`return sites?.filter((site) =>`

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by KateMashkinaNIH** [comment]
no longer an issue https://react-app-dev.cancer.gov/clinical-trials-search-app/develop/r?loc=0&q=CANscriptTM&rl=2
