### ISSUE TITLE
Two page titles are displayed on the invalid criteria page 

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/clinical-trials-search-app#495]
### Issue description

When we navigate to https://react-app-dev.cancer.gov/clinical-trials-search-app/pr-478/r?a=190&loc=0&rl=1 where one of the parameters has an invalid value ( in this case the age=190) - it shows the invalid criteria page with two titles (two H1s). Screen-shot is attached.

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  
2. 
3. 

### What's the expected result?
-

### What's the actual result?
-

### Additional details / screenshot

![image](https://user-images.githubusercontent.com/28455973/157895083-aca5d29f-5481-4fd2-aa4a-b3520d6e88a4.png)

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by alerosad** [comment]
Think this was solved by https://github.com/NCIOCPL/clinical-trials-search-app/issues/494, since on the current develop I don't see this issue

**Comment by alinai** [comment]
Looks good on https://react-app-dev.cancer.gov/clinical-trials-search-app/pr-501/r?a=190&loc=0&rl=1. Thanks @alerosad for fixing it and letting me know where I can verify it.

**Comment by sarinapadilla** [comment]
This was fixed by PR #494, so closing this ticket.
