### ISSUE TITLE
Search results are not showing "including X locations near you" filter in the Location field for Hospitals/Institutions searches

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/clinical-trials-search-app#531]
### Issue description

When we enter any institution to the "At Hospital/Institution" field, react-app-dev returns similar results, but none of them returns results displaying "including X locations near you".

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  Go to https://react-app-dev.cancer.gov/clinical-trials-search-app/develop/r?hos=Adams%20Cancer%20Center&loc=3&rl=2
2.  Notice that the search results are not showing ", including X location near me" using the filter "Adams Cancer Center" in the Location field on search results.

### What's the expected result?
- The search results should have locations near user using the Filter Adams Cancer Center.

### What's the actual result?
- Search results are returned with no location near me using the filter "Adams Cancer Center".

### Additional details / screenshot

Screenshot provided by @adriancofie:

![image](https://user-images.githubusercontent.com/28455973/173403915-b66b593b-9370-4c2c-9bf5-aef2d8583c98.png)

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by sarinapadilla** [comment]
@alinai "including X near you" shouldn't display for Hospitals/Institutions, since they don't use zip code data at all (unlike other searches). Prod and react-app-dev are working as expected, so closing this ticket!
