### ISSUE TITLE
Double horizontal lines are displayed when there is no pager at 1024px and lower

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/clinical-trials-search-app#532]
Double horizontal lines appear below the Start Over | Modify Search Criteria link and above the delighters at the bottom of the page at 1024px and lower on react-app-dev.

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  Go to https://react-app-dev.cancer.gov/clinical-trials-search-app/develop/r?loc=0&rl=1&t=C80078
2.  Switch the screen to 1024 px or lower
3. Double horizontal lines are displayed when there is no pager at 1024px and lower

### What's the expected result?
- There should be no horizontal lines when there is no pager present like desktop. See screenshot.
- Padding can be removed from top above "Select all on page" but should stay at bottom between "Select all on page" and the large icons (Have a question, here to help).

![Clinical-Trials-Search-Results---National-Cancer-Institute](https://user-images.githubusercontent.com/4921685/174798715-0fa7e3e2-b8e1-4db5-b5fd-2c510e96ce2c.jpg)

### What's the actual result?
- Double horizontal lines are displayed when there is no pager at 1024px and lower.

@mworrest , @sarinapadilla , please provide the AC/ Expected Result.

### Additional details / screenshot 

![image](https://user-images.githubusercontent.com/28455973/174343899-cacb89f4-b5a6-4b4a-88fe-11ae937b11fe.png)
![image](https://user-images.githubusercontent.com/28455973/174344002-4ef5b0d5-3af0-406a-8e77-63eb098f6234.png)

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by alinai** [comment]
@alerosad , The length of the search criteria box is longer than Prod, ODE and develop at all breakpoints.

![image](https://user-images.githubusercontent.com/28455973/180453054-bc7f928e-0983-4912-ba1e-b1f583c52cb8.png)
![image](https://user-images.githubusercontent.com/28455973/180453146-25dfd213-a0e0-4364-914e-10bed514276c.png)

**Comment by sarinapadilla** [comment]
This PR looks good to me on react-app-dev!
