### ISSUE TITLE
Duplicate NCI study protocol identifier not showing in Secondary IDs list

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/clinical-trials-search-app#560]
### Issue description
The Secondary IDs list is not displaying the Duplicate NCI Study Protocol Identifier that is returned in other_ids when viewing a trial description page.

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  Go to https://ncigovcdode450.prod.acquia-sites.com/about-cancer/treatment/clinical-trials/search/v?id=NCI-2018-02261&loc=0&rl=1&t=C2989

### What's the expected result?
- Secondary IDs list displays NCI-2018-02261, 97-C-0143, NCI-2013-02071

### What's the actual result?
- Secondary IDs list displays NCI-2018-02261, 97-C-0143

### Additional details / screenshot
- ODE:
<img width="1119" alt="Screen Shot 2022-07-26 at 10 30 08 AM" src="https://user-images.githubusercontent.com/24591940/181033535-1d632232-bdfc-4ba5-95c0-76df76bd876e.png">

- PROD:
<img width="1121" alt="Screen Shot 2022-07-26 at 10 30 24 AM" src="https://user-images.githubusercontent.com/24591940/181033611-85c873bf-ff74-4a11-8c7e-1e0438a8fdac.png">

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by SupriyaSaxena0605** [comment]
Verified on ODE. Looks good.
