### ISSUE TITLE
Trials with Trial Type "Other" should display "Not provided by clinicaltrials.gov"

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/clinical-trials-search-app#562]
### Issue description
The trial description page displays "Other" as the trial type for trials that return primary_purpose: "OTHER". This needs to be updated to say "Not provided by clinicaltrials.gov"

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  Go to https://ncigovcdode450.prod.acquia-sites.com/about-cancer/treatment/clinical-trials/search/v?id=NCI-2018-02261&loc=0&rl=1&t=C2989
2. Open the Trial Phase & Type accordion section

### What's the expected result?
- Trial Type is "Not provided by clinicaltrials.gov"

### What's the actual result?
- Trial Type is "Other"

### Additional details / screenshot
- ![Screenshot]()

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by SupriyaSaxena0605** [comment]
Verified on ODE. Looks good.
