### ISSUE TITLE
Page Not found (PNF) page retains the search term in the Search input box.

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/clinical-trials-search-app#577]
### Issue description

After performing search on Page Not found (PNF) page, we are redirected to the Site Wide Search results page and using browser back option we see that PNF retains its search term.

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  Go to https://ncigovcdode487.prod.acquia-sites.com/about-cancer/treatment/clinical-trials/search/foo
2. Enter "cancer" in the Search input box
3. Perform search
4. You will be redirected to the Site Wide Search results page 
5. Go back to the previous page using the "Go back" option of the browser.
6. PNF retains the search term in the Search input box.

### What's the expected result?
- PNF should NOT retain the search term in the Search input box.

### What's the actual result?
- PNF retains the search term in the Search input box.

### Additional details / screenshot
- ![Screenshot]()

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by seyilonge-nci** [comment]
ODE 487 no longer exists as this has been deployed to production. I wasn't able to reproduce this on cancer.gov in FF and Chrome.

**Comment by alinai** [comment]
Thanks @seyilonge-nci for checking. I am also not seeing the issue on Prod on Chrome, FF, Edge anymore. We can close this ticket.
