### ISSUE TITLE
Update npm security vulnerabilities

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/clinical-trials-search-app#585]
There are a number of security vulnerabilities that should be fixed via `npm audit fix`.

> **ESTIMATE** 2

### Notes
- This has the potential to break things as dependencies are updated to newer versions. Application functionality must be tested thoroughly.

**Comment by seyilonge-nci** [comment]
An npm audit report generated the file attached below
[cts-npm-audit-report-before.txt](https://github.com/NCIOCPL/clinical-trials-search-app/files/9697067/cts-npm-audit-report-before.txt)

Ran npm audit fix successfully

npm run test ran successfully with no errors

Running npm audit generated file attached below
[cts-npm-audit-report-after.txt](https://github.com/NCIOCPL/clinical-trials-search-app/files/9697078/cts-npm-audit-report-after.txt)
