### ISSUE TITLE
Update app to use node 16 and npm 6

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/clinical-trials-search-app#594]
### Issue description
Update the `engines` in package.json to the new versions, and update the GH workflow. We will also have to update package-lock.json to use the new npm format.

As part of this ticket, we need to update to the newest release of the `cgov-react-app-playground` shared workflow.

> **ESTIMATE** 2

### Additional details / screenshot
- ![Screenshot]()

### Related Tickets
* React App Playground: https://github.com/NCIOCPL/cgov-react-app-playground/issues/74

**Comment by alerosad** [comment]
Gives an error that seems to do with sass, when updating to node 16 and npm 8

```
Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (93)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.14.1
```

**Comment by alerosad** [comment]
The tests don't run too, when ran it throws an error involving cypress. Potential cypress update may be needed
