### ISSUE TITLE
Run npm audit fix and resolve remaining moderate or above vulnerabilities

### ISSUE THREAD

**Issue by adriancofie** [NCIOCPL/clinical-trials-search-app#621]
This ticket is to resolve any moderate and above vulnerabilities related to this repository.  

## Requirements: 

First run `npm audit` and `npm audit fix`, then address the remaining vulnerabilities.

In the commit comment take not of which packages were updated to which version, and any other pertinent information or steps taken.

## Acceptance Criteria:

All major and above NPM vulnerabilities are resolved.

**Comment by sarinapadilla** [comment]
Closing this ticket, since it'll be covered by #624.
